### ISSUE TITLE
Connection Indicators for ScopeSync Out not working on SS128A

### ISSUE THREAD

**Issue by bcsharc** [bcmodular/scopesync#75]
The Data and Dest output connectors on the SS128A module don't have connection indicators showing. I think this might just be down to the naming of the pads on the module - should be 'Data Output' and 'Dest Output' instead of 'data' and 'dest'.

**Comment by wellis** [comment]
Is this fixed in the latest SS128A?

**Comment by wellis** [comment]
Closing this down, as it relates to the audio-based version of ScopeSync, which is now retired.
